apiVersion: apps/v1
kind: Deployment
metadata:
  name: techtrends
  namespace: {{ .Values.namespace.name }}
  labels:
    app: techtrends
    tag: latest
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: techtrends
      tag: latest
  template:
    metadata:
      labels:
        app: techtrends
        tag: latest
    spec:
      containers:
      - name: techtrends
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        livenessProbe:
          httpGet:
            port: {{ .Values.readinessProbe.port }}
            path: {{ .Values.livenessProbe.path }}
        readinessProbe:
          httpGet:
            port: {{ .Values.readinessProbe.port }}
            path: {{ .Values.readinessProbe.path }}
        ports:
        - containerPort: {{ .Values.containerPort }}
        resources:
{{ toYaml .Values.resources | indent 12 }}