apiVersion: v1
kind: Service
metadata:
  name: techtrends
  labels:
    app: techtrends
    tag: latest
  namespace: {{ .Values.namespace.name }}
spec:
  selector:
    app: techtrends
    tag: latest
  ports:
  - port: {{ .Values.service.port }}
    protocol: {{ .Values.service.protocol }}
    {{ if .Values.service.targetPort}}
    targetPort: {{ .Values.service.targetPort }}
    {{ else }}
    targetPort: {{ .Values.service.port }}
    {{ end }}
  type: {{ .Values.service.type }}