apiVersion: apps/v1
kind: Deployment
metadata:
  name: techtrends
  namespace: sandbox
  labels:
    app: techtrends
    tag: latest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techtrends
      tag: latest
  template:
    metadata:
      labels:
        app: techtrends
        tag: latest
    spec:
      containers:
      - name: techtrends
        image: syarahmadi/tech-trends:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            port: 3111
            path: /healthz
        readinessProbe:
          httpGet:
            port: 3111
            path: /healthz
        ports:
        - containerPort: 3111