apiVersion: v1
kind: Service
metadata:
  name: techtrends
  labels:
    app: techtrends
    tag: latest
  namespace: sandbox
spec:
  selector:
    app: techtrends
    tag: latest
  ports:
  - port: 4111
    protocol: TCP
    targetPort: 3111
  type: ClusterIP